"""empty message

Revision ID: 56f9f7bdd4ed
Revises: d4302f1ab31b
Create Date: 2023-12-11 09:45:56.523875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f9f7bdd4ed'
down_revision = 'd4302f1ab31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nuevo_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['nuevo_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nuevo_token')

    # ### end Alembic commands ###
